### ISSUE TITLE
Which uom library should I be using?

### ISSUE THREAD

**Issue by aontas** [unitsofmeasurement/jackson-module-unitsofmeasure#18]
There is this library (obviously) and there is also this: https://github.com/unitsofmeasurement/uom-lib/tree/master/jackson

Which should I be using? Is there a reason that there are two (that I may have overlooked)?

**Comment by keilw** [comment]
This one is there for legacy purposes only, and although it has not been archived, only smaller bug-fixes are expected to happen. The UCUM support is already at 0.9, I guess it should also get to Unit Systems 1.0, but beyond that neither uom-se nor this Jackson module for JSR 363 are likely to be supported any longer. So they are as is and the repository will then be archived, too. 

https://github.com/unitsofmeasurement/uom-lib/tree/master/jackson uses the back-port of Indriya (1.0 still JSR 363 as well) and the corresponding new UCUM library. Wich UCUM 1.0 the Indriya version and API should reach the 2.0 level in EDR stage. So there it'll use JSR 385. JSR 363 is Final, so it depends if you must use an officially final API or you are happy to use the Draft of 2.0? They are both equally stable, but 2.0 could be subject to change here and there before the Final release. The uom-lib version is more future-proof. 

HTH?

**Comment by aontas** [comment]
Thanks for the lengthy response, that does help.

I wanted to push what I would consider a bug fix (that occurs in both places), so I guess I'll make a PR for both so that they can at least stay in sync for now.
